### ISSUE TITLE
[1.1.7b RC1 regression, forum portion] If you use the back button after reading the result (a thread or a post) of a search request, you don't go back to the search results, you go to the subscribed threads tab instead

### ISSUE THREAD

**Issue by Wood-Man** [Wood-Man/XDA-Labs-Issues-and-Suggestions#102]
When you search something, you get the search results page, you hit one result, read the post/thread and then hit the back button. After doing this you don't go back to the search results (you go to the subscribed threads and then if you hit the back button, you reach the search results finally)

**Comment by zacharee** [comment]
Fixed https://github.com/zacharee/XDA-Labs/commit/33ec56dcfc65b549c76cf3ce62b6cc26b804358a

**Comment by Wood-Man** [comment]
Yes I can confirm it's fixed. Thanks!
