### ISSUE TITLE
Can't download attachment

### ISSUE THREAD

**Issue by eliaspizarro** [Wood-Man/XDA-Labs-Issues-and-Suggestions#95]
Try this in xdalabs app

https://forum.xda-developers.com/devdb/project/?id=27466#downloads

**Comment by Wood-Man** [comment]
Hi,

This is not a bug, because this devdb tab (download tab) is not a forum or a thread. XDA Labs can't handle this. Please read here for more info: https://forum.xda-developers.com/showpost.php?p=66786837&postcount=3302
